ci: add verify secret keys in commits with husky

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,1 +1,51 @@
+GIT_SECRETS_PATH="/usr/local/bin/git-secrets"  # Adjust this path if necessary
+# Section for git-secrets
+if [ ! -x "$GIT_SECRETS_PATH" ]
+# if ! command -v git-secrets &> /dev/null
+then
+   echo "git-secrets is not installed. Please run 'brew install git-secrets' or visit https://github.com/awslabs/git-secrets#installing-git-secrets"
+   exit 1
+fi
+
+# Clean all existing git-secrets patterns first
+git config --local --unset-all secrets.patterns 2>/dev/null || true
+git config --local --unset-all secrets.allowed 2>/dev/null || true
+
+# Custom REGEX patterns Array to check for various custom secrets
+patterns="sk_live_[0-9a-zA-Z]{99} sk_test_[0-9a-zA-Z]{99} rk_live_[0-9a-zA-Z]{99} ghp_[0-9a-zA-Z]{36} gho_[0-9a-zA-Z]{36} ghs_[0-9a-zA-Z]{36} ghr_[0-9a-zA-Z]{36} AKIA[0-9A-Z]{16} AIza[0-9A-Za-z_-]{35} xox[baprs]-[0-9a-zA-Z]{10,48} npm_[0-9a-zA-Z]{36} eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+"
+
+# Log file path
+log_file="git_secrets.log"
+
+# Function to add a pattern if it does not already exist
+add_pattern_if_not_exists() {
+ pattern="$1"
+ existing_patterns=$(git secrets --list 2>>"$log_file")
+echo "pattern===" $pattern
+ if echo "$existing_patterns" | grep -Fqe "$pattern"; then
+   echo "Pattern '$pattern' already exists. No need to add."
+ else
+   echo "Pattern '$pattern' not found. Adding pattern..."
+   git secrets --add "$pattern" 2>>"$log_file"
+   if [ $? -eq 0 ]; then
+     echo "Pattern '$pattern' added successfully."
+   else
+     echo "Failed to add pattern '$pattern'."
+     exit 1
+   fi
+ fi
+}
+
+# Iterate over the space-separated list of patterns and add them if they don't exist
+for pattern in $patterns; do
+ add_pattern_if_not_exists "$pattern"
+done
+
+echo "Running git-secrets..."
+# This command will scan whole codebase and will report any sensitive information where pattern is matched.
+git-secrets --scan -r
+
+# Scans only the files that are about to be committed.
+# git-secrets --pre_commit_hook -- "$@"
+
 npx commitlint --edit $1
